[package]
name = "loucura"
version = "0.0.0"
edition = "2021"

[dependencies]
cranelift = "0.111.0"
cranelift-module = "0.111.0"
cranelift-object = "0.111.0"
pest = "2.7.11"
pest_derive = "2.7.11"
target-lexicon = "0.12.16"
